@startuml

class User {
    String id
    String lastname
    String firstname
    String email
    String role
    String password
}


class Expenditure {
    String id
    String description
    Double amount
    String contributor_id
    String group_id
}

class Group {
    String id
    String name
    String description
}

class Contributor {
    String group_id
    String user_id
}


Contributor ||..o{ Expenditure
Group ||..o{ Expenditure
User ||..o{ Contributor
Group ||..o{ Contributor


@enduml
